# Generated by Django 2.2 on 2020-08-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='本のタイトル')),
                ('author', models.CharField(max_length=255, verbose_name='著者')),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
